### ISSUE TITLE
Location offset

### ISSUE THREAD

**Issue by 809004** [EpicGames/MetaHuman-DNA-Calibration#10]
I modify the dna in maya which import use "dna_viewer_run_in_maya.py";
Then i export a modified dna use "dna_viewer_grab_changes_from_scene_and_propagate_to_dna.py";
Last i export a fbx from the modified dna use "dna_viewer_demo.py";
Now i get a modified face mesh in unreal engine, I have reset the asset details such as material slots、post process anim blueprint、asset user data...and so on. then i set the modified face mesh to the metahuman BP, there is an obvious location offset:
![1](https://user-images.githubusercontent.com/86150179/208654430-7cc98700-fc9b-4471-81db-d4c8803d0484.png)
Original metahuman like this:
![3](https://user-images.githubusercontent.com/86150179/208654600-54faa3f7-1a26-439b-ab36-26cde0301b28.png)
Even if i adjust the location, there is a obvious crack between head and body:
![2](https://user-images.githubusercontent.com/86150179/208654936-866322c1-fec0-41a4-95b5-800b993978c4.png)

**Comment by 809004** [comment]
i forget set something, i find out...

**Comment by 809004** [comment]
I remove Animation set, it seems normal , but we can't play animation without 'Face_AnimBP_C'.
![1](https://user-images.githubusercontent.com/86150179/208682717-dc7f2175-7dcc-4390-b51e-37f936ce2223.png)

**Comment by rmedina-ea** [comment]
I don't know about the cheeks, but I think the neckline issue you are seeing might be due to the body settings on your MetaHuman. The dna_viewer_demo.oy example grabs the body skeleton from data/body/fem_skeleton.ma, but if your MetaHuman is not the same height / build as Ada, the merging might not yield the results you are expecting. Hope it helps.

**Comment by 809004** [comment]
> 

I tried your suggestion, problem solved, thank you very much.

**Comment by smilicev** [comment]
@rmedina-ea thanks.

@809004 if you have any additional questions, feel free to post them.
