### ISSUE TITLE
i cant find dna in  "MetaHuman_DNA_Calibration\dna_viewer\util"

### ISSUE THREAD

**Issue by AchooLiu** [EpicGames/MetaHuman-DNA-Calibration#11]
i cant find dna in  "MetaHuman_DNA_Calibration\dna_viewer\util"

maya gives me this error : 
ImportError: cannot import name 'BinaryStreamReader' from 'dna_viewer.reader.dna' (D:/Autodesk/MetaHuman_DNA_Calibration\dna_viewer\reader\dna.py) #

hope I can get some help，thanks  a lot!

**Comment by smilicev** [comment]
Hi @AchooLiu, 

What script are you trying to run?
Did you change `ROOT_DIR` from that script?

If you are running some hand made script can you put it in whole here, so I can see it and pinpoint a problem for you?

**Comment by smilicev** [comment]
Hi @AchooLiu,

Did you manage to resolve your issue?

**Comment by AchooLiu** [comment]
When I run the code on another computer, the error disappears. I don't know what happened, but the problem was solved.
thank you very much!
