### ISSUE TITLE
adding remove joints in a command Sequence Queue

### ISSUE THREAD

**Issue by SSGC-ShapeShifters** [EpicGames/MetaHuman-DNA-Calibration#12]
hi, I am trying to queue up a sequence for removing joint commands with something like, however the wrong joints removed are always wrong.

#print ("dict", dna_joint_index_dict)      
for joint_name in joint_filter_list:    
        joint_index = dna_joint_index_dict[joint_name]
        #print (get_joint_name, joint_name)
        # Removes joint with specified index
        remove_joint_command = dnacalib.RemoveJointCommand(joint_index)
        # Queue up 
        commands.add(remove_joint_command)

Then I calibrate the dna after every joint removal and it works, as my assumption is that the index for joint changes as you start to remove joint, so if I queue up remove joint based on the dict made before the command sequence starts, as soon as the first joint is removed, the rest of the index will be wrong

remove_joint_command = dnacalib.RemoveJointCommand(joint_index)
        # Modifies calibrated DNA in-place
        remove_joint_command.run(calibrated)

        print(f"Successfully removed joint `{joint_name}` with index number `{joint_index}`.")

**Comment by smilicev** [comment]
Hi, `CommandSequance` is not smart, so in order to delete joints, you need it reverse list, and delete from back.
Hope this helps.

**Comment by smilicev** [comment]
Hi @SSGC-ShapeShifters, did you manage to fix your issue?

**Comment by djiangvfx** [comment]
sorry for the super late reply! The previous github account has some issue. I am David Jiang, who have asked the question! The solution is very smart and totally works for the need! 

I got a follow up question regarding propagate changes in scene tool, it seems like the function requires every bone in every lod of a metahuman to exist inside both dna and scene for it work, if a joint its missing, it will error out.

**Comment by smilicev** [comment]
If you are thinking about https://github.com/EpicGames/MetaHuman-DNA-Calibration/blob/main/examples/dna_viewer_grab_changes_from_scene_and_propagate_to_dna.py, you are right, we need all joints and lods and order of joints has to be same as in DNA, if that is not achieved, you will have some error, or DNA which is bad.

Can you provide me a script that you are using?

**Comment by YuhongIrene** [comment]
hi ！
when I run the example code of https://github.com/EpicGames/MetaHuman-DNA-Calibration/blob/dc377a79f26f1bda17c81f658c8a93c4ca5eecc7/examples/dnacalib_remove_joint.py. I can successfully remove the joint in dna file.

But the riglogic control of the metahuman cannot be used anymore, To avoid the problem of the joint index, I just remove the lastest index of the joint.(Like the number 886 joint.).But the controller still cannot use. Could you please                                                                tell me what is the problem? What else should I do to make this system can be used after remove or add some joints?

**Comment by smilicev** [comment]
Deleting joint is destructive action. Rig logic needs all joints in order to work. So after that action you cannot create functional rig. But you can use build_meshes functionality. 

I will close this issue. If you have other issues, open new issue for that.
