### ISSUE TITLE
how to adjust body

### ISSUE THREAD

**Issue by 809004** [EpicGames/MetaHuman-DNA-Calibration#13]
I am confused that how can i adjust body mesh ?  I can't find some document about this.

**Comment by lordofinsomnia** [comment]
Adjusting body mesh is not part of this library. Body mesh is added as an example. Anything that needs to be changed on body is on your own. But maybe I can help, what do you want to accomplish?

**Comment by smilicev** [comment]
Adjusting body mesh is not part of this library. Body mesh is added as an example. Anything that needs to be changed on body is on your own. But maybe I can help, what do you want to accomplish?

**Comment by 809004** [comment]
Since exporting face fbx from dna needs body's ma file, if I adjust body's bone, the face mesh must be distorted. Do you have any advice on how to adjust body's bone?

**Comment by smilicev** [comment]
You can 
- open generated maya scene, 
- change position and or orientation, in order to fit our head. 
- delete rig, and leave just objects in scene that are in original body file (https://github.com/EpicGames/MetaHuman-DNA-Calibration/tree/main/data/body)
- generate new scene with script, and iterate this steps until you are satisfied with generated maya scene.

**Comment by hanson1985** [comment]
Hi can I scale body rig with dna? I need to scale rig for live mocap session with actor. Actor size are different from provided rig. I need corect size to match actor becouse he will interact with objects.

**Comment by smilicev** [comment]
As mentioned [here](https://github.com/EpicGames/MetaHuman-DNA-Calibration/issues/17#issuecomment-1437994819).

You have to use `ScaleCommand`, for more details read it's [documentation](https://epicgames.github.io/MetaHuman-DNA-Calibration/dnac.html#classdnac_1_1ScaleCommand)
