### ISSUE TITLE
I compile your code on MacOS according your Installation README, but generated 'dylib' can't be used by your code.

### ISSUE THREAD

**Issue by shoutOutYangJie** [EpicGames/MetaHuman-DNA-Calibration#14]
It occurs the  "ModuleNotFound" error

> ModuleNotFoundError: No module named '_py3dna'

the generated files can be seen as following.
<img width="484" alt="image" src="https://user-images.githubusercontent.com/46734514/210314476-32a279b7-d6c6-4650-b152-8b472d75658e.png">

**Comment by smilicev** [comment]
Hi @shoutOutYangJie can you try to force cmake to generate .pyd files insted of .dylib?
```
    set_property(TARGET py3dna PROPERTY PREFIX "pyd")
    set_property(TARGET py3dna PROPERTY OUTPUT_NAME "_py3dna.pyd")
```

If this does not help, please send me a message here. So we can fix your issue.

**Comment by smilicev** [comment]
I will close this issue. @shoutOutYangJie if your problem persists, provide me more details, so I can help.
