### ISSUE TITLE
Scale joints in DNA

### ISSUE THREAD

**Issue by Skladka** [EpicGames/MetaHuman-DNA-Calibration#17]
Hey! it is necessary to reduce the size of the body to one meter in height. I go through the DNA, freeze the transforms, unload, but the new model does not quite correctly work out the movement of the lips, unlike the original model. Any ideas how to fix it?

**Comment by djiangvfx** [comment]
to scale DNA globally (mesh, joints, rig logic). Use this command instead:

 `ScaleCommand(value, [pivotX, pivotY, pivotZ])`

transforming and rotating then freezing the joint will effectively change the placement of the joint inside of DNA but it will not affect the scale of motion inside the dna, so I suggest first scale the DNA with ScaleCommand first then change the placement of the joints

**Comment by smilicev** [comment]
@djiangvfx is right, in order to properly scale rig in DNA, you have to use `ScaleCommand`, For more details read it's [documentation](https://epicgames.github.io/MetaHuman-DNA-Calibration/dnac.html#classdnac_1_1ScaleCommand)
@djiangvfx Thanks. 

I will close this issue.
