### ISSUE TITLE
Overlapping modules and paths with dna and _py3dna with incompatible binaries when loaded with Quixel bridge

### ISSUE THREAD

**Issue by wywarren** [EpicGames/MetaHuman-DNA-Calibration#19]
There are numerous overlapping modules in this repo that coincide with the modules load in version 6.x and 7.x of the Quixel Bridge Maya plugin. When used in conjunction in Maya 2022, from a fresh load the dna_viewer and the bridge works initially. But once one of the two loads `_py3dna`, the corresponding dna.py in the other repo path will complain about missing classes and functions. Are there plans to consolidate the compiled binaries into one unified compiled module we can reference or how can we proceed with this? 

Older versions of the maya plugin can be found here: https://quixel.com/plugins/

The latest 7.0 is downloaded with the Quixel Bridge desktop client or via the link here: https://quixel-megascans-static.s3.us-west-2.amazonaws.com/bridge/plugins_12/maya/win/7.0.zip

**Comment by smilicev** [comment]
We are aware of this issue. In our next release this issue is going to be fixed. In order that your script works you need to add [setup environment snippet](https://github.com/EpicGames/MetaHuman-DNA-Calibration/blob/5d19123f0c2f3d6b2b80edd11ac19e14fdaf15b8/examples/dna_viewer_demo.py#L45). 

```
from os import environ, makedirs
from os import path as ospath
from shutil import copyfile
from sys import path as syspath
from sys import platform

# if you use Maya, use absolute path
ROOT_DIR = f"{ospath.dirname(ospath.abspath(__file__))}/..".replace("\\", "/")
OUTPUT_DIR = f"{ROOT_DIR}/output"
DATA_DIR = f"{ROOT_DIR}/data"
ROOT_LIB_DIR = f"{ROOT_DIR}/lib"
if platform == "win32":
    LIB_DIR = f"{ROOT_LIB_DIR}/windows"
elif platform == "linux":
    LIB_DIR = f"{ROOT_LIB_DIR}/linux"
else:
    raise OSError(
        "OS not supported, please compile dependencies and add value to LIB_DIR"
    )

# Add bin directory to maya plugin path
if "MAYA_PLUG_IN_PATH" in environ:
    separator = ":" if platform == "linux" else ";"
    environ["MAYA_PLUG_IN_PATH"] = separator.join([environ["MAYA_PLUG_IN_PATH"], LIB_DIR])
else:
    environ["MAYA_PLUG_IN_PATH"] = LIB_DIR

# Adds directories to path
syspath.insert(0, ROOT_DIR)
syspath.insert(0, LIB_DIR)
syspath.insert(0, DATA_DIR)
```

If this does not help with your issue. Please reopen this issue, provide me with more information.

**Comment by wywarren** [comment]
We are already using this snippet. An example in our use case and we're getting differences in the `_py3dna` libraries being called with `DNAHolder` on the quixel bridge import which is calling different stream libraries than the ones in this repo. It uses `_pydna.StreamReader` while the one in this repo seems to be using `BinaryStreamReader` and `JSONStreamReader` which the default quixel one doesn't have.

In this case we're getting:
`Error: DHI.modules.maya.util : No constructor defined - class is abstract`

inside `DNAHolder` after the `dna_viewer` is imported and we try to import an asset from quixel.
