### ISSUE TITLE
error loading DNA

### ISSUE THREAD

**Issue by SofiePT** [EpicGames/MetaHuman-DNA-Calibration#2]
`# RuntimeError: Error loading DNA: DNA signature mismatched, expected DNA, got ver`
After trying to load DNA through dna_viewer_run_in_maya.py

**Comment by vvukobrat** [comment]
Hi! Could you please check the size of the DNA file that was checked out?
It should be ~70MB.
It's possible that yours is only ~1KB, in which case, you should install git lfs on your side, and then try to check it out again.
If you don't want to setup git lfs for some reason, you could also just download it manually.
Let me know if this answers your problem.

**Comment by smilicev** [comment]
Hi @SofiePT, thanks for reporting an issue. @vvukobrat was right. 

Here is detailed explanation.

DNA files are stored as [LFS](https://git-lfs.github.com/) files. (At the moment site of git LFS is down, and here is [another explanaintion](https://www.atlassian.com/git/tutorials/git-lfs) what LFS is. You probably downloaded this repo as zip, and github then does not download LFS files as whole file, but as some metadata file.  If you open that Ada.dna file in some editor file, from location were you downloaded MetaHuman-DNA-Calibration and then in `data/dna/Ada.dna` (eg `c:/MetaHuman-DNA-Calibration/data/dna/Ada.dna` you will got this:

```
version https://git-lfs.github.com/spec/v1
oid sha256:e764cfab938283231bcb3e5af1c7bcbec5154bab4804aafa1b5b7dc6e400ca5e
size 73730354
```
Which is not valid DNA file.

You have two options:
- use git clone `git clone https://github.com/EpicGames/MetaHuman-DNA-Calibration.git` 
- or manually download [Ada.dna](https://github.com/EpicGames/MetaHuman-DNA-Calibration/blob/main/data/dna/Ada.dna) and/or [Taro.dna](https://github.com/EpicGames/MetaHuman-DNA-Calibration/blob/main/data/dna/Taro.dna), and put them in data directory where you downloaded MetaHuman-DNA-Calibration. eg. `c:/MetaHuman-DNA-Calibration/data/dna`

I will close this issue. If your problem persists, please reopen it and provide us with more details.

**Comment by Clairezsh** [comment]
Hi, I  manually downloaded Ada.dna, but this problem is still remain，I still got this:
`Traceback (most recent call last):
  File "D:/DNA-Calibration-pc/examples/dnacalib_demo.py", line 195, in <module>
    main()
  File "D:/DNA-Calibration-pc/examples/dnacalib_demo.py", line 191, in main
    calibrate_dna(args.input_dna, args.output_dna)
  File "D:/DNA-Calibration-pc/examples/dnacalib_demo.py", line 160, in calibrate_dna
    dna = load_dna(input_path)
  File "D:/DNA-Calibration-pc/examples/dnacalib_demo.py", line 81, in load_dna
    raise RuntimeError(f"Error loading DNA: {status.message}")
RuntimeError: Error loading DNA: DNA signature mismatched, expected DNA, got ver`
Is there any other problem?
