### ISSUE TITLE
Overlapping modules and paths with dna and _py3dna with incompatible binaries when loaded with Quixel bridge

### ISSUE THREAD

**Issue by wywarren** [EpicGames/MetaHuman-DNA-Calibration#20]
There are numerous overlapping modules in this repo that coincide with the modules load in version 6.x and 7.x of the Quixel Bridge Maya plugin. When used in conjunction in Maya 2022, from a fresh load the `dna_viewer` or the bridge metahuman import works initially. But once one of the two loads, _py3dna, the corresponding dna.py in the other repo path will complain about missing classes and functions. Are there plans to consolidate the compiled binaries into one unified compiled module we can reference or how can we proceed with this?

Older versions of the maya plugin can be found here: https://quixel.com/plugins/

The latest 7.0 is downloaded with the Quixel Bridge desktop client or via the link here: https://quixel-megascans-static.s3.us-west-2.amazonaws.com/bridge/plugins_12/maya/win/7.0.zip

Steps to reproduce:

1. Open Quixle Bridge with Maya 7.0 Plugin
2. Open up Maya 
3. Load the `dna_viewer` from this repo using:
```from os import environ, makedirs
from os import path as ospath
from shutil import copyfile
from sys import path as syspath
from sys import platform

# if you use Maya, use absolute path
ROOT_DIR = f"{ospath.dirname(ospath.abspath(__file__))}/..".replace("\\", "/")
OUTPUT_DIR = f"{ROOT_DIR}/output"
DATA_DIR = f"{ROOT_DIR}/data"
ROOT_LIB_DIR = f"{ROOT_DIR}/lib"
if platform == "win32":
    LIB_DIR = f"{ROOT_LIB_DIR}/windows"
elif platform == "linux":
    LIB_DIR = f"{ROOT_LIB_DIR}/linux"
else:
    raise OSError(
        "OS not supported, please compile dependencies and add value to LIB_DIR"
    )

# Add bin directory to maya plugin path
if "MAYA_PLUG_IN_PATH" in environ:
    separator = ":" if platform == "linux" else ";"
    environ["MAYA_PLUG_IN_PATH"] = separator.join([environ["MAYA_PLUG_IN_PATH"], LIB_DIR])
else:
    environ["MAYA_PLUG_IN_PATH"] = LIB_DIR

# Adds directories to path
syspath.insert(0, ROOT_DIR)
syspath.insert(0, LIB_DIR)
syspath.insert(0, DATA_DIR)

from dna_viewer import show_dna_viewer_window
show_dna_viewer_window()
```
4. Close the `dna_viewer` window
5. Import any metahuman from Quixel Bridge
6. Run into an error on `DNAHolder` (class inside quixel Maya 7.0 plugin) with `Error: DHI.modules.maya.util : No constructor defined - class is abstract`.

Things I've tried:

1. Unloading `_py3dna` and `dna` and reimporting to resolve the missing libraries (`BinaryStreamReader` and `JSONStreamReader`) not present in quixel's version. With the `dna_viewer` loaded first, quixel's import function is using the existing `dna` and `_py3dna` modules rather than its own from the 7.0 plugin.

**Comment by smilicev** [comment]
New version of DNACalibration is released on Friday. Which addresses issue that you stumbled upon.  
Here are steps how to [setup environment](https://github.com/EpicGames/MetaHuman-DNA-Calibration#environment-setup). 

Bridge is going to be updated soon, so we don't have this issues anymore.
I will close this issue. If you stumble upon more problems, feel free to create new issue.
