### ISSUE TITLE
SWIG tool error when compile pydna

### ISSUE THREAD

**Issue by Steven9402** [EpicGames/MetaHuman-DNA-Calibration#21]
I compiled the dnaclib using the command as follows:

> cd dnacalib
> mkdir build
> cd build
> cmake  -DPYTHON3_EXACT_VERSION=3.9 -DDNAC_LIBRARY_TYPE=SHARED ..
> cmake --build . --config Release

but failed with error:
>C:\dna_calibration\dnacalib\build\py3bin\DNAPYTHON_wrap.cxx(19338,47): error C2065: “SWIG_Fr”: 未声明的标识符 [C:\dna_calibration\dnacalib\build\PyDNA\python3\py3dna.vcxproj]

then I opened DNAPYTHON_wrap.cxx, the last lines are:
>  SWIG_Python_SetConstant(d, "Direction_down",SWIG_From_int(static_cast< int >(dna::Direction::down)));
>  SWIG_Python_SetConstant(d, "Direction_front",SWIG_From_int(static_cast< int >(dna::Direction::front)));
>  SWIG_Python_SetConstant(d, "Direction_back",SWIG_Fr

Obviously it is not a complete cxx file. Seem the problem is Swig can not generate a complete cxx file.
I am using Swig 4.0.0, and I also tried Other versions, but the same problem.

Also, when I compiled 'PyDNACalib', the 'DNACalibPYTHON_wrap.cxx' file generated by Swig is not complete.

**Comment by Steven9402** [comment]
@smilicev Any help would be Appreciate. Thanks

**Comment by smilicev** [comment]
This looks strange. Can you switch to US localization? And try again, but delete `build` directory.

**Comment by smilicev** [comment]
I will close it due to inactivity. If you provide me more details you can reopen this issue.
