### ISSUE TITLE
Maya2023 error when using compiled dna.py

### ISSUE THREAD

**Issue by Bymeoryou** [EpicGames/MetaHuman-DNA-Calibration#22]
Hello, I have compiled the dnaclib using the command as follows:
```shell
cd dnacalib
mkdir build
cd build
cmake -DPYTHON3_EXACT_VERSION=3.9 -DDNAC_LIBRARY_TYPE=SHARED ..
cmake --build . --config Release
```
it builds successful and I also copy the five files below to the **MetaHuman-DNA-Calibration\lib\windows** folder: 
```shell
dna.py
_py3dna.pyd
dnacalib.dll
dnacalib.py
_py3dnacalib.pyd
```
However, when I want to create a DNA reader in maya2023, it shows:
```shell
NameError: file /dna/lib/window/dna.py line 359: name 'FileStream_create' is not defined
```
 Any help would be Appreciate. Thanks

**Comment by smilicev** [comment]
Version 1.1.0 with support for Maya 2023 is released. I am closing this issue. If you find any new problems. Feel free to open new issue for that.
