### ISSUE TITLE
Maya python- It's trying to get the DNA.py module from the wrong location

### ISSUE THREAD

**Issue by mussupaa** [EpicGames/MetaHuman-DNA-Calibration#23]
So I had dnacalib working before. But then i opened up a character from quixel bridge. And now it is looking at the wrong dna.py file. So I get an error with any of the example scripts.

# Error: ImportError: file <maya console> line 33: cannot import name 'BinaryStreamReader' from 'dna' (F:/BX/Bridge/support/plugins/maya/7.0/MSLiveLink/DHI/lib/Windows/python3\dna.py)

I have tried setting the module path in maya.env to no avail. How can I reset the location used for the dna module?

**Comment by smilicev** [comment]
I presume that you used [this](https://github.com/EpicGames/MetaHuman-DNA-Calibration#environment-setup) to setup your environment?

If you still have problems, try to reorder or even delete Bridge from `MAYA_MODULE_PATH`, and restart Maya after that.
With newer version of Bridge this issue will be fixed. Release date for Bridge is TBD.

**Comment by mussupaa** [comment]
Oh I had tried updating maya.env instead of adding MAYA_MODULE_PATH as a system variable. It now works, thanks for your response!

**Comment by smilicev** [comment]
Great! I will close this issue then.
