### ISSUE TITLE
Convert fbx to dna

### ISSUE THREAD

**Issue by RioLei** [EpicGames/MetaHuman-DNA-Calibration#24]
I have a file fbx, I want to convert fbx to dna. How to work? Please help me, thanks.

**Comment by smilicev** [comment]
I'm afraid that won't be possible. It works just in one direction, DNA -> FBX.

**Comment by RioLei** [comment]
Can you tell me why I can't convert from fbx to dna?

**Comment by smilicev** [comment]
FBX contains geometry with baked animations. We cannot convert back that animations to our internal model. 
What are you trying to do? Maybe you don't need to convert FBX to DNA.
