### ISSUE TITLE
Error when run "dna_viewer_run_in_maya" example

### ISSUE THREAD

**Issue by Dahi154** [EpicGames/MetaHuman-DNA-Calibration#25]
Hi! This error show up when I try to run "dna_viewer_run_in_maya" example.
# Error: ModuleNotFoundError: file C:\Program Files\Autodesk\Maya2022\Python37\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py line 142: No module named 'dna_viewer' # 

Did I add MetaHuman DNA Calibration files in wrong MAYA_MODULE_PATH?
I just copy it in "C:\dna_calibration"

**Comment by Dahi154** [comment]
On the orther hand, if I try some way that make the viewer code run 
then I try to run "dna_viewer_grab_changes_from_scene_and_propagate_to_dna" example.
I got new error :(
# # dna_viewer.common.DNAViewerError: Something went wrong, skipping adding the rig logic... Reason: Plug-in, "embeddedRL4.mll", was not found on MAYA_PLUG_IN_PATH.

# Error: DNAViewerError: file C:\Users\hiend\Documents\support\plugins\maya\7.0\MSLiveLink\DHI\dna_viewer\builder\rig_builder.py line 91: Something went wrong, skipping adding the rig logic... Reason: Plug-in, "embeddedRL4.mll", was not found on MAYA_PLUG_IN_PATH. # 

Can you help me solve this, please?

**Comment by smilicev** [comment]
Hi @Dahi154, you did not setup your environment. Here is a [link ](https://github.com/EpicGames/MetaHuman-DNA-Calibration#environment-setup) how to do it.

**Comment by Dahi154** [comment]
It was quiet complicated for me. Now it work!
Thank you so much!
