### ISSUE TITLE
Plug-in, "embeddedRL4.mll", was not found on MAYA_PLUG_IN_PATH.

### ISSUE THREAD

**Issue by haoqicainiao** [EpicGames/MetaHuman-DNA-Calibration#27]
在maya中使用dna_viewer.show()导入dna。出现"embeddedRL4.mll"丢失的报错，但是我maya插件列表中是有存在的，从bridge导入metahuman角色也是正常的。有和我一样遇到这个问题的么？
![K@QPB{RT402DS2_%12R JQW](https://github.com/EpicGames/MetaHuman-DNA-Calibration/assets/104479739/e39138c5-6a18-44d7-986e-39773c67a33e)
![N{K }G89LH@$HGSCLL)0ROK](https://github.com/EpicGames/MetaHuman-DNA-Calibration/assets/104479739/921f482f-d042-4dc2-8900-4039987e8603)

**Comment by N1zNEVER** [comment]
请问，你是怎么解决的啊？？
Excuse me, how did you solve it?
