### ISSUE TITLE
 json_to_dna_binary

### ISSUE THREAD

**Issue by zhumeichoubao** [EpicGames/MetaHuman-DNA-Calibration#30]
After I ran dna_binary_to_json_demo.py, I modified some data in the json file, how can I convert this json file into a dna_binary file now?

**Comment by marijavik** [comment]
Unfortunately, we cannot read the JSON file at the moment. I would advise you to make changes you did manually in the JSON file using writer and set commands. Would it be possible?

```
stream = FileStream(dna_path, FileStream.AccessMode_Write, FileStream.OpenMode_Binary)
writer = BinaryStreamWriter(stream)
writer.setFrom(reader)

writer.set…
writer.write()
```

**Comment by marijavik** [comment]
Closing this issue, in case more information needed, please reopen it.
