### ISSUE TITLE
DNA Calib command to write blenshapes - grab_changes_from_scene_and_propagate_to_dna

### ISSUE THREAD

**Issue by booomji** [EpicGames/MetaHuman-DNA-Calibration#33]
Hello,
I want to swap the mh head mesh for a custom one with a few minor tweaks. My custom mesh has the exact same topology as the original mh (  I have just added some tweaks over the original mh). 

The example file "grab changes from scene and propagate" only allows me to deform the mesh using joint transforms. 
I'd rather add a blendshape to make the original mh fit the modified mh head in maya.
What command or process should I be using to achieve this ?  

Is there a process to add the target mesh in the blend shape editor and bake the changes out ?

Thank you so, so much for any help as I have been struggling with this for days now.

b

**Comment by booomji** [comment]
Eureka ! 

I have documented the process of adding a blend shape and swapping out the original head with a custom one using the same script.
It worked for me. I hope this works for you too.

[documented example file for blendshape](https://github.com/booomji/MetaHuman-DNA-Calibration/blob/main/examples/dna_viewer_grab_changes_from_scene_and_propagate_to_dna.py)

**Comment by smilicev** [comment]
@booomji Thanks for reporting this issue. 
I have made changes in https://github.com/EpicGames/MetaHuman-DNA-Calibration/blob/main/examples/dna_viewer_grab_changes_from_scene_and_propagate_to_dna.py. I will close this issue.
