### ISSUE TITLE
MayaUERBF 2024 support

### ISSUE THREAD

**Issue by Haxxer** [EpicGames/MetaHuman-DNA-Calibration#35]
I'm a user of your Maya RBF plugin and have been eagerly awaiting its compatibility with Maya 2024 - Are you able provide an estimated timeline or any information regarding when we can expect Maya 2024 compatibility?

**Comment by marijavik** [comment]
Hello @Haxxer,

I still do not have any information when it will be available, but make sure to check Quixel bridge periodically as it will be first supported there.

**Comment by marijavik** [comment]
Bridge is updated and support for Maya 2024 is added there.

**Comment by marijavik** [comment]
Hello @Haxxer,

the support for Maya 2024 has been added yesterday in 1.3.0 release.

**Comment by kalebzaki4** [comment]
It sounds like you're keen to see the RBF plugin compatible with Maya 2024! For the most accurate information on timelines or updates regarding compatibility, it’s best to check the official channels for the plugin, such as the developer's website, forums, or social media pages. They often provide updates on new releases and compatibility issues. If there's a community forum, you might also find discussions about anticipated release dates or beta testing opportunities there. 

If you have specific concerns or needs regarding the plugin, reaching out directly to the support or development team could also yield useful insights!
