### ISSUE TITLE
The problem with the seam in Unreal

### ISSUE THREAD

**Issue by HI4AN** [EpicGames/MetaHuman-DNA-Calibration#36]
Hi, I use DNA and I have a problem with the seam and eyes in Unreal. In maya, I made all the settings I needed, everything looks very good, but after I import FBX into Unreal and apply the original MH materials, I have unnecessary shading on my eyes when using the green channel, if I switch the channel to all, the problem with the eyes is solved, but a distinct seam appears between the head and body, caused by incorrect operation of normals, how can I fix it? I tried a lot of ways, re-transformed the attributes of normals in maya, experimented with different settings for exporting from maya and importing to Unreal, but I could not solve this problem, most likely I'm missing something in unreal, but I can't figure out what
![1691bda2b0ce2d1d2fb71d9d3d7dcb631b4db100](https://github.com/EpicGames/MetaHuman-DNA-Calibration/assets/118726953/489d8217-9968-4535-8647-595bdffc53b7)
![be0350e4c4bb464b0a6f75a7f6c82adc07328246](https://github.com/EpicGames/MetaHuman-DNA-Calibration/assets/118726953/0e9d0ec8-708b-4eb6-9599-b3febeb21b5c)
![d9789f6fc0e8c3e69de9d3373cef0951013bfe85](https://github.com/EpicGames/MetaHuman-DNA-Calibration/assets/118726953/04dbda61-e14d-4ba8-8653-4ecf5408b986)

**Comment by marijavik** [comment]
Hi,

maybe the issue here is that during FBX export `vtx_color` variable had False value - it should be True.
This can be checked on LOD0 FBX file by:

![image (1)](https://github.com/EpicGames/MetaHuman-DNA-Calibration/assets/35915685/fbb50ba3-cbe2-47f7-9fca-865f3e744cbe)
If the head is black - vtx_color was False.
If that is the case, set this True and export files again.

**Comment by HI4AN** [comment]
> Привет,
> 
> возможно, проблема здесь в том, что во время экспорта FBX `vtx_color`переменная имела значение False - оно должно быть True. Это можно проверить в файле LOD0 FBX с помощью:
> 
> ![изображение (1)](https://user-images.githubusercontent.com/35915685/280270986-fbb50ba3-cbe2-47f7-9fca-865f3e744cbe.png) Если голова черная - значение vtx_color было ложным. Если это так, установите значение True и экспортируйте файлы снова.



> Hi,
> 
> maybe the issue here is that during FBX export `vtx_color` variable had False value - it should be True. This can be checked on LOD0 FBX file by:
> 
> ![image (1)](https://user-images.githubusercontent.com/35915685/280270986-fbb50ba3-cbe2-47f7-9fca-865f3e744cbe.png) If the head is black - vtx_color was False. If that is the case, set this True and export files again.

Hello again, sorry I didn't ask this earlier, but I'm clearly doing something wrong, even if I import the original MH into maya, I can't get the same result as in your screenshot, I don't have a head color, the color is only on the body, if you add a shader, the head becomes all black if I remove the material, the head becomes completely green, what could be the problem? And I also can't find the item you mentioned ("If that is the case, set this True and export files again"), where exactly can I set the value "true" in the settings?
![321321](https://github.com/EpicGames/MetaHuman-DNA-Calibration/assets/118726953/140579ec-e61b-4e49-9565-9a9d2de27643)
![2342435](https://github.com/EpicGames/MetaHuman-DNA-Calibration/assets/118726953/6c90939a-8b9d-4570-a74f-3f4818a921a3)
