### ISSUE TITLE
Facial Controllers are missing / changed after DNA Calibration

### ISSUE THREAD

**Issue by miCPTR** [EpicGames/MetaHuman-DNA-Calibration#37]
<img width="916" alt="2023-12-11_14-09-40" src="https://github.com/EpicGames/MetaHuman-DNA-Calibration/assets/124721074/ad6d69d7-7b9d-4465-afbc-53166e8f1dce">

Hello, I noticed some facial controllers are missing or changed after I made DNA calibration following the example of propagating changes from Maya scene to dna file (examples/dna_viewer_grab_changes_from_scene_and_propagate_to_dna.py). Any ideas?

**Comment by marijavik** [comment]
Hello,

DNA calibration process would only update DNA file itself, it would not touch other files at all. In your case you used 2 different gui,ma files. On the [left](https://github.com/EpicGames/MetaHuman-DNA-Calibration/blob/main/data/gui.ma) and on the [right](https://github.com/EpicGames/MetaHuman-DNA-Calibration/blob/main/data/mh4/gui.ma).
If you use UE 5.2 or 5.3 the correct gui file is on the right.
In [README ](https://github.com/EpicGames/MetaHuman-DNA-Calibration?tab=readme-ov-file#example-dna-files) there is a section with explanation which files should be used in examples.
