### ISSUE TITLE
Dose DNACalib support writing certain data to dna file?

### ISSUE THREAD

**Issue by aigcoder** [EpicGames/MetaHuman-DNA-Calibration#39]
Hi, 
Dose DNACalib support writing certain data (liking head vertices or joints only, rather than the whole things) to dna file?
Currently it's very time comsuming to write all the infos to dna file (about 10 seconds), and actually we usually just only need to update part of dna file.
And if DNACalib supports this feature, how can I achieve this? 
Thanks a lot!

**Comment by marijavik** [comment]
Hello @aigcoder,

There is no option to partially write a DNA file. However, the team is working on optimization of write operation so it should be much faster in general.

**Comment by aigcoder** [comment]
Thanks for your reply.
Looking forward to the optimized DNA writer. :)
