### ISSUE TITLE
> I have added the code to the mod file to make it work with Maya 2024.

### ISSUE THREAD

**Issue by MyhostRL** [EpicGames/MetaHuman-DNA-Calibration#66]
> I have added the code to the mod file to make it work with Maya 2024.
> 
> ```
> + MAYAVERSION:2024 PLATFORM:win64 MetaHuman-DNA-Calibration any .
> PYTHONPATH +:=
> PYTHONPATH +:= data
> PYTHONPATH +:= lib/Maya2024/windows
> MAYA_PLUG_IN_PATH +:= lib/Maya2024/windows
> ```
> 
> This will enable the plugin to work with Maya 2024 as it will show up in the plugins folder. Otherwise Maya will look in the Quixel bridge folder which does not work with Maya 2024

_Originally posted by @MyhostRL in https://github.com/EpicGames/MetaHuman-DNA-Calibration/pull/62#pullrequestreview-2491421484_

**Comment by marijavik** [comment]
Updated in 1.3.1 release.
