### ISSUE TITLE
Skeleton Tree 

### ISSUE THREAD

**Issue by 809004** [EpicGames/MetaHuman-DNA-Calibration#9]
I get a face mesh from dna data, but the root of the skeleton tree is "spine_04". so how can i reimport the face mesh to unreal engine with the correct skeleton?

**Comment by smilicev** [comment]
In [dna_viewer_demo.py](https://github.com/EpicGames/MetaHuman-DNA-Calibration/blob/9f035971edd6f80a6b7ae6623d33bf5281dc6766/examples/dna_viewer_demo.py#L152) we have subset for exporting fbx. I have marked function that you have you can take a look. You can just run `dna_viewer_demo.py` and it will generate fbx for you, and then you can import it in unreal engine.

**Comment by 809004** [comment]
I have tried the export function in "dna_viewer_demo.py", it successfully exports fbx from modified dna. but I still can't use the face  mesh in unreal directly, because all the submesh combine to one, am i missing some settings?

**Comment by smilicev** [comment]
Use clean version of `dna_viewer_demo.py`, and it should generate fbx that is ready for import in unreal engine. Did you change something `dna_viewer_demo.py`?

**Comment by 809004** [comment]
no , i just change the ROOT_DIR.

**Comment by 809004** [comment]
![1](https://user-images.githubusercontent.com/86150179/208572690-c60f81cd-d69e-4095-b626-1668e195f6f9.png)
I import the generated fbx in unreal engine ,Material Slots like this.

**Comment by smilicev** [comment]
Mine imported fbx imported into unreal engine is on the right, and yours is on the left.
![image](https://user-images.githubusercontent.com/21858368/208640459-b696aea4-4710-4734-82f6-1093544e48c7.png)

In output directory you got multiple fbxes for one for each lod.
Can you send me Ada_lod0.fbx, and Ada.dna from output dir?

**Comment by 809004** [comment]
I found out the operation of mesh combine is due to unreal engine's fbx import function. I can reset different material on submesh to avoid combining.

**Comment by smilicev** [comment]
Great. I will close this issue. If you find some other problem. Feel free to open new issue.

**Comment by 809004** [comment]
wait a moment, i find a new problem

**Comment by smilicev** [comment]
I am listening.
